### PR TITLE
Add JVM flags to optimize startup time

### PR DESCRIPTION
**Pull request by dsyer**

### CODE REVIEW

**Comment by markfisher** [comment]
I'm not seeing any difference in startup time for either `stream.sh` or `web.sh`.

**Comment by dsyer** [comment]
Really? It should have some effect at least. It ought to be more noticeable with the thin jars (that PR has a bug in it I think though).

**Comment by markfisher** [comment]
`task.sh` is faster (~1.2 seconds as opposed to ~2.1 seconds for me)

**Comment by markfisher** [comment]
okay - well I rebased and merged this anyways

**Comment by markfisher** [comment]
rebased and merged as https://github.com/markfisher/spring-cloud-function/commit/a8141d96a7ec6336c42a7ab2b76ff81c3d8f3ac8

**Pull request closed without merging**
