### PR TITLE
Update thin launcher to 1.0.0.M1

### PR DESCRIPTION
**Pull request by dsyer**

### CODE REVIEW

**Comment by markfisher** [comment]
build succeeded, but while running through the README examples, I hit this failure on the first `web.sh` app startup:

```Parameter 0 of method messageChannelToInputFluxArgumentAdapter in org.springframework.cloud.stream.reactive.ReactiveSupportAutoConfiguration required a bean of type 'org.springframework.cloud.stream.converter.CompositeMessageConverterFactory' that could not be found.```

That's a bean that should be implicitly provided via the `@EnableBinding` I believe (cc @mbg), but I'm not sure how that would have been impacted by the thin launcher update.

**Comment by mbg** [comment]
You probably meant to mention someone else...

**Comment by mbogoevici** [comment]
Yeah, that should be provided via `@EnableBinding` - not sure why it is missing. Since it's a web example, I guess it's missing `@EnableBinding`. It's probably a bug in `spring-cloud-stream-reactive` - we shouldn't enable that autoconfiguration if the Stream beans aren't present.

**Comment by markfisher** [comment]
yes @mbg I apologize for the noise - was instinctively using a different handle for my colleague...  I edited right away but you still got the notification. I will delete your message above as well as this one. sorry!

**Comment by markfisher** [comment]
there is no `@EnableBinding` in this case, because none of the conditions here are satisfied: https://github.com/markfisher/spring-cloud-function/blob/master/spring-cloud-function-stream/src/main/java/org/springframework/cloud/function/stream/StreamConfiguration.java

however, even adding `--spring.cloud.stream.enabled=false` to the `web.sh` command (where it invokes `java -jar`) does not avoid the error... so indeed it must be the auto-config within the `spring-cloud-stream-reactive` dependency itself

**Comment by mbogoevici** [comment]
@markfisher Tracing this in https://github.com/spring-cloud/spring-cloud-stream/issues/775

**Comment by mbogoevici** [comment]
This was caused by changing Stream from `Brooklyn.B-S` to `Brooklyn.SR1` (which misses a fix for this issue introduced after SR1). Use `Brooklyn.SR2` instead.

**Comment by markfisher** [comment]
thanks @mbogoevici - that did the trick!

**Pull request merged**
