### PR TITLE
Fix deployer app

### PR DESCRIPTION
**Pull request by dsyer**
Run it, then

$ curl localhost:8080/admin
{"sample":{"name":"sample","id":"81c568e36c7909ec1dd841aa7ee6d3e3","path":"..."}}

undeploy:

$ curl localhost:8080/admin/sample -X DELETE
{"id":"81c568e36c7909ec1dd841aa7ee6d3e3"}

redeploy

$ curl localhost:8080/admin/sample -d path=maven://com.example:function-sample-pojo:1.0.0.BUILD-SNAPSHOT
{"id":"81c568e36c7909ec1dd841aa7ee6d3e3"}

(Takes about 500ms)

### CODE REVIEW

**Comment by markfisher** [comment]
I am seeing nothing near 500ms. 3 runs were all just over 10.5 seconds...

```
Started application in 10.637 seconds (JVM running for 153.397)
```

**Comment by dsyer** [comment]
That's odd. Maybe snapshot resolution. Did you have s-c-function built locally?

**Comment by dsyer** [comment]
Is your 10s the time to start the deployer app or the time to start the function? I tried it on my slowest laptop:

```
2017-05-21 16:08:21.868  INFO 15528 --- [       Thread-9] o.s.boot.SpringApplication               : Started application in 0.771 seconds (JVM running for 57.653)
```

**Comment by markfisher** [comment]
I ran `./mvnw clean install` right before trying this. I'm referring to the time for the deploy (after the deployer app itself is already running). I'm also using a brand new laptop.

**Comment by dsyer** [comment]
Update: Mark fixed his `/etc/hosts` (MacOS Sierra) to resolve localhost properly, and it fixed this slow startup issue.

**Comment by markfisher** [comment]
Yes. I'm now seeing an average app deployment time of about 600ms. Nice!

**Pull request merged**
